openapi: "3.0.0"
info:
  title: "Billing"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "rraiyani62@gmail.com"

host: "localhost:3007/api"
apis: ["./src/components/**/*.route.js"]
schemes: ["https"]
